default-lease-time 900;
max-lease-time 7200;

subnet 192.168.171.0 netmask 255.255.255.0 {
        option routers 192.168.171.2;
        range 192.168.171.20 192.168.171.250;
        option subnet-mask 255.255.255.0;
        option domain-search "ocp.koko";
        option domain-name-servers 192.168.171.40;
        next-server 192.168.171.40;
        option ntp-servers 1192.168.171.40; 
        if exists user-class and option user-class = "iPXE" {
                filename "http://bastion.ocp.koko:8080/boot.ipxe";
        } else {
                filename "undionly.kpxe";
        }
}

host bootstrap {
        hardware ethernet 00:1a:4a:16:01:20;
        fixed-address 192.168.171.50;
        option host-name "bootstrap.ocp.koko";
}

host master-0 {
        hardware ethernet 00:1a:4a:16:01:29;
        fixed-address 192.168.171.41;
        option host-name "master-0.ocp.koko";
}

host master-1 {
        hardware ethernet 00:1a:4a:16:01:2a;
        fixed-address 192.168.171.42;
        option host-name "master-1.ocp.koko";
}

host master-2 {
        hardware ethernet 00:1a:4a:16:01:2b;
        fixed-address 192.168.171.43;
        option host-name "master-2.ocp.koko";
}

host cptnod-0 {
hardware ethernet d0:67:e5:a1:34:3e;
fixed-address 192.168.171.46;
option host-name "cptnod-0.ocp.koko";
}

host cptnod-1 {
hardware ethernet d0:67:e5:e4:87:1e;
fixed-address 192.168.171.47;
option host-name "cptnod-1.ocp.koko";
}
